base_url: "http://www.tmradio.net/"
title: "Тоже мне радио"
disqus_id: tmradio
flattr_name: tmradio
language: ru_RU
ueb_pattern: "https://github.com/tmradio/tmradio-website/edit/master/%s"
strip_urls: yes


# Описание RSS-каналов.
feeds:
- name: rss.xml
  title: "Тоже мне радио"
  description: "Все обновления сайта tmradio.net"
- name: podcast.xml
  title: "Подкасты"
  description: "Подкасты на tmradio.net"
  labels: [podcast]
- name: mcast.xml
  title: "Микроподкасты"
  description: "Микроподкасты на tmradio.net"
  labels: [mcast]
  limit: 65535
- name: live.xml
  title: "Прямые эфиры"
  description: "Все прямые включения на tmradio.net"
- name: hotline.xml
  title: "Горячая линия"
  description: "Сообщения с горячей линии"
  labels: [hotline]
- name: tsn.xml
  title: "Так себе новости"
  description: "Так себе новости на Тоже мне радио"
  labels: [tsn]


buttons:
  labels: [podcast, blog]
  prefix: "Поделиться:"
  items:
  - title: Поделиться ВКонтакте
    link: "http://vkontakte.ru/share.php?url=%(url)s&amp;image=%(image)s"
    caption: ВКонтакте
    type: vkontakte
  - title: Поделиться в Facebook
    link: "http://www.facebook.com/sharer/sharer.php?u=%(url)s&amp;t=%(title)s"
    caption: Facebook
    type: facebook
  - title: Отправить в Twitter
    caption: Twitter
    link: "https://twitter.com/intent/tweet?text=%(title)s%%3A+%(url)s"
    type: twitter
  - title: Поддержать материально
    link: "https://flattr.com/submit/auto?user_id=tmradio&amp;url=%(url)s&amp;title=%(title)s&amp;description=%(summary)s&amp;language=ru_RU&amp;tags=%(labels)s&amp;category=%(category)s"
    caption: Flattr
    type: flattr

authors:
- name: микроша
  email: info@tmradio.net
  website: "http://twitter.com/tmradio"
  avatar: "http://a2.twimg.com/profile_images/1535580971/62494941_normal.jpg"
- name: umonkey
  email: hex@umonkey.net
  website: "http://umonkey.net/"
  fullname: "Хекс"
- name: dugwin
  email: dugwin@gmail.com
  website: "http://www.dugwin.net/"
  fullname: "dugwin j. goines"
- name: partyzan
  email: rubyis@yandex.ru
  avatar: "http://a0.twimg.com/profile_images/1213968238/avvatar_normal.jpg"
- name: sckrat
  email: sckrat.lipetsk@gmail.com
  website: "http://sckrat.ru/"
  flattr_name: SckraT_
- name: rustray
  email: info@tmradio.net
- name: nikonor
  email: nikonor@gmail.com
  profile: "http://about.me/nikonor"
- name: hakimovis
  email: hakimovis@gmail.com
  website: "https://twitter.com/hakimovis"
  fullname: "Ирик Хакимов"
- name: argbrontsterop
  email: argbrontsterop@gmail.com
  website: "https://twitter.com/argbrontsterop"
  fullname: "Хасан Атаман"
  avatar: "https://twimg0-a.akamaihd.net/profile_images/669489147/He_s_RED_normal.jpg"
- name: 505796
  email: 505796@bk.ru
  fullname: "Сапунов Виталий Витальевич"
- name: gagarin
  email: gagarintl@ya.ru
  fullname: "Гагарин Артём"
  profile: "/guests/gagarin/"
- name: iPtrX
  email: ptrx.mail@googlemail.com
  profile: "/guests/iptrx/"
- name: paskal
  fullname: "Дмитрий Паскаль"
  email: info@tmradio.net
  avatar: "https://twimg0-a.akamaihd.net/profile_images/1150762784/e6d1f3a3efd104176cbb2644d58eab410c09ec6d_reasonably_small"
- name: trump
  fullname: "Олег Козинцев"
  email: o.kozintsev@googlemail.com
  avatar: "https://twimg0-a.akamaihd.net/profile_images/1572159272/z_a2c51f91_normal.jpg"
- name: steeker
  fullname: "Семеон Бобошко"
  email: OnlySemeon@gmail.com
- name: dreamin
  title: "Сергей Король"
  website: "http://ctrl-c-writer.ru/"

sections:
- tsn
- prokino
- suddenly
- mcast
- hotline
- podcast
- blog

labels:
- name: tsn
  title: Так себе новости
  link: /programs/tsn/
  rss_file: programs/tsn/index.xml
  default_summary: "Обсуждение новостей последней недели."
- name: tsn-dry
  title: Выжимки из ТСН
  link: /programs/tsn-dry/
- name: suddenly
  title: Вдруг
  link: /programs/suddenly/
  rss_file: programs/suddenly/index.xml
  default_summary: "Беседы с интересными людьми под спокойную музыку."
- name: mcast
  title: Микроподкасты
  link: /programs/mcast/
  rss_file: programs/mcast/index.xml
- name: prokino
  title: Про кино
  link: /programs/prokino/
  rss_file: programs/prokino/index.xml
- name: podcast
  title: Подкасты
  link: /podcast/
  rss_file: podcast/index.xml
- name: hotline
  title: Горячая линия
  link: /hotline/
  rss_file: hotline/index.xml
- name: blog
  title: Блог
  link: /blog/
  rss_file: blog/index.xml
- name: umonkey
  title: umonkey
  link: /guests/umonkey/
  rss_file: guests/umonkey/rss.xml

comment_labels:
- blog
- podcast
